### PR TITLE
Major refactoring of release script

### PR DESCRIPTION
**Pull request by zakkak**
* Splits code into classes to group together related functionality
* Uses picocli subcommands instead of manually checking whether the user requested a "release" or "prepare" _phase_
  * This also enables us to have subcommand specific flags, e.g. `-d` doesn't make sense in `prepare`
* Decouples the code for each subcommand hopefully making it a bit easier to understand/follow what each command does

Probably best reviewed commit by commit.

### CODE REVIEW

**Comment by Karm** [comment]
THX @zakkak, lemme try

**Comment by Karm** [comment]
@zakkak 
It seems to me the `-m` option is not being taken into account:

```
$ ./mandrel-release.java release -s Beta1 -m /tmp/mandrel-release-test -f Karm/mandrel-demo-release
[jbang] Building jar...
java.nio.file.NoSuchFileException: ./substratevm/mx.substratevm/suite.py
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at java.base/java.nio.file.Files.newBufferedReader(Files.java:2922)
	at java.base/java.nio.file.Files.readAllLines(Files.java:3412)
	at java.base/java.nio.file.Files.readAllLines(Files.java:3453)
	at MandrelVersion.ofRepository(mandrel-release.java:162)
	at Release.call(mandrel-release.java:1045)
	at Release.call(mandrel-release.java:1023)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at MandrelRelease.main(mandrel-release.java:99)
```

I can see that this
```
 @CommandLine.Option(names = {"-m", "--mandrel-repo"},
        scope = CommandLine.ScopeType.INHERIT,
        description = "The path to the mandrel repository",
        defaultValue = "./")
    String mandrelRepo;
```

passes on the default value `./`   

The file indeed exists here: `/tmp/mandrel-release-test/substratevm/mx.substratevm/suite.py`

...any hints?

**Comment by zakkak** [comment]
The following seems to work (moving the common parameters before the subcommand):
```
./mandrel-release.java -s Beta1 -m /tmp/mandrel-release-test -f Karm/mandrel-demo-release release
```

So it looks like `scope = CommandLine.ScopeType.INHERIT` doesn't do exactly what I thought....

Looking into it...

**Comment by Karm** [comment]
Hmm, we need to either change the code or change the Readme then :-D

**Comment by Karm** [comment]
I don't have any definite idea on the UX of the command....

**Comment by Karm** [comment]
```
## Creating an Alpha or Beta pre-release

### Step 1: Tags creation

First we need to create a tag.

```
git checkout mandrel/20.2
git pull upstream mandrel/20.2
git tag -a mandrel-20.2.0.0.Beta2 -m "mandrel-20.2.0.0.Beta2" -s
git push upstream mandrel-20.2.0.0.Beta2
```

Make sure to create the same tag in the `mandrel-packaging` repository.

### Step 2: Create pre-release

Then `./mandrel-release.java release -s Beta2 -m <path/to/mandrel> -f <username/mandrel-fork>` must be invoked which is responsible for:
```

@zakkak Do we still support creating Alpha/Beta releases? The code seems to suggest we do, but then again:

```
$ ./mandrel-release.java release -s Beta1 -m /tmp/mandrel-release-test -f Karm/mandrel-demo-release --verbose
[INFO] Current version is 23.0.0.0
[ERROR] No milestone titled 23.0.0.0-Final! Can't produce changelog without it!
karm@ovpn-194-186:~/workspaceRH/mandrel-packaging-zaaakak/release-scripts (major-ref
```

I don't think we produced it since 20.x era though...

**Comment by zakkak** [comment]
> I don't think we produced it since 20.x era though...

Yes, I think we broke this somewhere along the way (by 1. not using it enough, and 2. not testing for it in the CI). Probably unrelated to this PR....

**Comment by zakkak** [comment]
> True, so not sure how well it works.

I tried it out and found an issue that I fixed with https://github.com/graalvm/mandrel-packaging/pull/289/commits/b5bc76673e0e48cb8cc495ff3c07a8822f728968, other than that it seems to work OK in my test.

**Comment by Karm** [comment]
THX @zakkak, I am having Github creating new fresh clones, via import, 
https://github.com/Karm/mandrel-release-test
and its
https://github.com/Karm/mandrel-release-test-fork
and I will run it again to see.  

I wonder whether to try to automate this to get some kind of test of the sanity of the release script....

**Comment by zakkak** [comment]
> I wonder whether to try to automate this to get some kind of test of the sanity of the release script....

That "would be nice", not sure how much effort it needs though. We can use `https://github.com/mandrel-bot` to avoid "polluting" our accounts.

**Comment by Karm** [comment]
Hello @zakkak, I played with it with @KarmBot and fake repos and I think It Works :tm: 

If you'd want to squash, squash and merge.

**Review by Karm — APPROVED** [review]

**Comment by zakkak** [comment]
Thanks Karm, I think I prefer keeping the history as is :)

**Pull request merged**
