### PR TITLE
Delegate maven deploy to `mx`

### PR DESCRIPTION
**Pull request by zakkak**
Closes: #220

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]
Ship it!

**Comment by zakkak** [comment]
> Ship it!

Thanks for the review @jerboaa!

I am waiting for some internal tests to pass before merging this.

**Comment by galderz** [comment]
Hmmm, please note my comments [here](https://github.com/graalvm/mandrel-packaging/pull/218/files#r782782517). You won't really know the impact of this until you're further down the line producing jars.

**Comment by zakkak** [comment]
> Hmmm, please note my comments [here](https://github.com/graalvm/mandrel-packaging/pull/218/files#r782782517). You won't really know the impact of this until you're further down the line producing jars.

This has been tested internally. The jars were built and pushed successfully (not released yet though). Hopefully since they passed the gates they are also OK for release.

**Pull request merged**
