### PR TITLE
Jenkins DSL scripts for 20.1 branch, see #81

### PR DESCRIPTION
**Pull request by Karm**
Just a port of #81

### CODE REVIEW

**Comment by zakkak** [comment]
Is this backport really necessary?

AFAIU the jenkins pipeline only needs the build scripts located under `jenkins/jobs/scripts`, do we need to backport the pipelines as well?

**Comment by Karm** [comment]
> Is this backport really necessary?
> 
> AFAIU the jenkins pipeline only needs the build scripts located under `jenkins/jobs/scripts`, do we need to backport the pipelines as well?

It is not necessary per se. It seemed more consistent to me to do it as 1:1 backport.  

Per rule of thumb less code = better, I will remove the groovy files here...

**Comment by Karm** [comment]
BTW: @zakkak Annoying lesson learned: Jenkins DSL != Jenkins Pipeline. The syntax looks vaguely similar, but these are two unrelated DSLs and looking at a guide/How-To for one does not help with the other.

**Comment by zakkak** [comment]
> BTW: @zakkak Annoying lesson learned: Jenkins DSL != Jenkins Pipeline. The syntax looks vaguely similar, but these are two unrelated DSLs and looking at a guide/How-To for one does not help with the other.

+1, I am mostly worried about inconsistencies between the groovy files across the two branches and potential confusion in the future.

**Comment by Karm** [comment]
@zakkak ping,
It needs a review & merge to work for the builds....   
Thx.

**Review by zakkak — APPROVED** [review]
Looks good, thanks Karm

**Pull request merged**
