### PR TITLE
 [24.1] Fixes version parsing for WARNING situations

### PR DESCRIPTION
**Pull request by Karm**
See https://github.com/graalvm/mandrel-packaging/pull/442#issue-2473551177

### CODE REVIEW

**Comment by jerboaa** [comment]
Is this a `git cherry-pick -x` commit from master?

**Comment by Karm** [comment]
@jerboaa 
```
 git cherry-pick ff3824b
```

**Comment by jerboaa** [comment]
> @jerboaa
> 
> ```
>  git cherry-pick ff3824b
> ```

Could you please use `-x` option so that we know it's from a master commit by looking at the git log output. Thanks!

**Comment by Karm** [comment]
> > @jerboaa
> > ```
> >  git cherry-pick ff3824b
> > ```
> 
> Could you please use `-x` option so that we know it's from a master commit by looking at the git log output. Thanks!

Done.

**Review by jerboaa — APPROVED** [review]

**Pull request merged**
