### PR TITLE
Add dependencies for building native-image-diagnostics-agent library

### PR DESCRIPTION
**Pull request by zakkak**
Like in #63 this PR builds and install all the necessary dependencies to build `native-image-diagnostics-agent.so` using:
`native-image --macro:native-image-diagnostics-agent-library`

The changes in this PR **DO NOT** build and install `native-image-diagnostics-agent.so`.

This new library is not available in XX.Y < 20.3 and merging this PR will make master non functional for 20.1.
As a result I open it as a Draft PR to discuss how we would like to approach this.

Note: GraalVM CE 20.3 is expected to be released on November 17 2020.

### CODE REVIEW

**Comment by galderz** [comment]
@zakkak We should branch for 20.1 to avoid merging things like this in a branch that is designed for 20.1.

**Review by galderz — APPROVED** [review]

**Comment by Karm** [comment]
@zakkak Needs conflicts resolution...

**Comment by zakkak** [comment]
Branch 20.1 is now a thing https://github.com/graalvm/mandrel-packaging/tree/20.1

**Comment by zakkak** [comment]
@Karm waiting for your approval before I merge (mainly to make sure that you are aware that this will break any scripts using `master` for building Mandrel 20.1)

**Review by Karm — APPROVED** [review]

**Comment by Karm** [comment]
@zakkak Got it.  So I will flip 20.1 builds to run off https://github.com/graalvm/mandrel-packaging/tree/20.1

**Pull request merged**
