### PR TITLE
[24.0] Backport: Introduce --disable-debuginfo-stripping option

### PR DESCRIPTION
**Pull request by zakkak**
Cherry picked commits from https://github.com/graalvm/mandrel-packaging/pull/388 to `24.0`

- Introduce `--disable-debuginfo-stripping` option
- [CI] Fetch compatible mx version instead of `master`
- [CI] Disable `--verbose` in CI runs, because it adds too much noise

### CODE REVIEW

**Comment by zakkak** [comment]
Looking in CI failures

**Comment by jerboaa** [comment]
It seems we need backports of #385 and #384 for 24.0?

**Comment by zakkak** [comment]
> It seems we need backports of #385 and #384 for 24.0?

No, it was building `graal/master` instead of `mandrel/24.0` it should be fixed now

**Comment by jerboaa** [comment]
> > It seems we need backports of #385 and #384 for 24.0?
> 
> No, it was building `graal/master` instead of `mandrel/24.0` it should be fixed now

OK, we need at least this work-around cherry-picked for MacOS X, though:
https://github.com/graalvm/mandrel-packaging/pull/384/commits/5780feff9739b17bd78b3139e6e7c80c7dd3c0d2

**Review by jerboaa — APPROVED** [review]

**Pull request merged**
