### PR TITLE
JDK 24, new Q demo link

### PR DESCRIPTION
**Pull request by Karm**

### CODE REVIEW

**Review by zakkak — APPROVED** [review]
LGTM, thanks @Karm

**Comment by jerboaa** [comment]
JDK 24 got me confused. The latest is JDK 23. I think you meant GraalVM 24.0 (internal version). Anyway, good for me.

**Comment by Karm** [comment]
Sorry, I meant 24.0.0.0.    I wonder how ordinary users handle the naming :-)

**Comment by zakkak** [comment]
@Karm @gastaldi suggests not using an extension at all as the names might change again. Not specifying an extension should bring `quarkus-rest` which includes the starter code.

Also note that `quarkus-resteasy` is not the old `quarkus-resteasy-reactive`.

**Comment by Karm** [comment]
@zakkak Thx. I read the Zulip after your conversation took place. You guessed correctly, back in the day this was the way to get starter example code too, not just an empty project. It seems that is not necessary any more.

**Pull request merged**
