### PR TITLE
Don't remove org.graalvm.compiler.truffle.compiler.hotspot.amd64

### PR DESCRIPTION
**Pull request by zakkak**
Works around issue https://github.com/graalvm/mandrel/issues/387 until https://github.com/oracle/graal/pull/4633 gets merged.

Closes https://github.com/graalvm/mandrel/issues/387

### CODE REVIEW

**Comment by jerboaa** [comment]
@zakkak Any ideas why GHA build is failing? Hopefully we don't need this workaround by getting the fix upstream.

**Comment by zakkak** [comment]
> @zakkak Any ideas why GHA build is failing? Hopefully we don't need this workaround by getting the fix upstream.

To my understanding https://github.com/oracle/graal/commit/123490eedd60969c3b903aafa7fe3e970652ec7a#diff-5c2805e0fef0535c28bff8559292cca73a8f81338c2ebe48f1e1039e9db3b68fL1600 removed the explicit dependency on `org.graalvm.compiler.truffle.compiler` (which was satisfying javac before) and now brings it in through `org.graalvm.compiler.truffle.compiler.hotspot.amd64` which we explicitly remove in mandrel-packaging (see https://github.com/oracle/graal/commit/123490eedd60969c3b903aafa7fe3e970652ec7a#diff-5c2805e0fef0535c28bff8559292cca73a8f81338c2ebe48f1e1039e9db3b68fR1856)

**Comment by Karm** [comment]
@zakkak Did this patch help the build for you locally? I might be doing something wrong, but it is the same for me (Windows 10)

```
Building Java module org.graalvm.nativeimage.objectfile (objectfile.jar) from OBJECTFILE
C:\tmp\mandrel\substratevm\src\com.oracle.svm.core\src\com\oracle\svm\core\meta\ObjectConstantEquality.java:28: error: package org.graalvm.compiler.truffle.compiler.nodes does not exist
import org.graalvm.compiler.truffle.compiler.nodes.ObjectLocationIdentity;
                                                  ^
1 error

```

**Comment by zakkak** [comment]
> @zakkak Did this patch help the build for you locally? I might be doing something wrong, but it is the same for me (Windows 10)

Interesting, yes it did work for me locally, but I will need to check on a clean env as well.

**Comment by Karm** [comment]
> > @zakkak Did this patch help the build for you locally? I might be doing something wrong, but it is the same for me (Windows 10)
> 
> Interesting, yes it did work for me locally, but I will need to check on a clean env as well. Scheduled tests on GHA:
> 
>     * linux: https://github.com/graalvm/mandrel/actions/runs/2468710121 heavy_check_mark
> 
>     * windows: https://github.com/graalvm/mandrel/runs/6813751026 hourglass_flowing_sand

The error was on my site. My mandrel source was not clean on Windows. The suites.py were already updated by an older run.

**Review by Karm — APPROVED** [review]
Works on my Windows 10 machine.

**Comment by jerboaa** [comment]
@zakkak Why are GHA failing with this? Is this pre-existing?

**Comment by zakkak** [comment]
> @zakkak Why are GHA failing with this? Is this pre-existing?

You mean GHA testing this PR right? These are failing because they are trying to build with the GA JDK, but `graal/master` currently only builds with EA JDK. That's known and OK, not sure if we should change this tests to use EA. It would probably make sense since whenever we change mandrel-packaging is for a future feature release. WDYT?

**Comment by jerboaa** [comment]
> > @zakkak Why are GHA failing with this? Is this pre-existing?
> 
> You mean GHA testing this PR right? These are failing because they are trying to build with the GA JDK, but `graal/master` currently only builds with EA JDK. That's known and OK, not sure if we should change this tests to use EA. It would probably make sense since whenever we change mandrel-packaging is for a future feature release. WDYT?

Ah, OK. Yes, please change it to use EA builds. It would be future proofing things that way.

**Review by jerboaa — APPROVED** [review]
Feel free to ship in the interim.

**Pull request merged**
